### ISSUE TITLE
Incorrect bit order

### ISSUE THREAD

**Issue by Mobivlad** [pidhoretskyi/Micro2#1]
You have to send 4 MSB bits at first:
https://github.com/pidhoretskyi/Micro2/blob/fbb2aa5d40ad8bb410be7bf3bc39aed1a06b0188/user/main.c#L59
And then 4 LSB bits:
https://github.com/pidhoretskyi/Micro2/blob/fbb2aa5d40ad8bb410be7bf3bc39aed1a06b0188/user/main.c#L54

**Comment by pidhoretskyi** [comment]
Thanks, done.
